### ISSUE TITLE
Does this extension support https for socket.io?

### ISSUE THREAD

**Issue by shamyne** [yiicod/yii2-socketio#13]
I have everything configured and running nicely with HTTP, but I get a connection error whenever I try using HTTPS.  What do I need to change to get it to work with HTTPS?

Thanks!

**Comment by lexxorlov** [comment]
Hello. You should set this for console config:
>     'controllerMap' => [
>         'socketio' => [
>             'ssl' => [
>                 'key' => '/etc/ssl/certs/xxxx.key',
>                 'cert' => '/etc/ssl/certs/xxxx.crt',
>             ]
>         ],
>     ],

**Comment by shamyne** [comment]
That worked!  Thank you!

**Comment by CarlosPSMora** [comment]
> Hello. You should set this for console config:
> 
> > ```
> > 'controllerMap' => [
> >     'socketio' => [
> >         'ssl' => [
> >             'key' => '/etc/ssl/certs/xxxx.key',
> >             'cert' => '/etc/ssl/certs/xxxx.crt',
> >         ]
> >     ],
> > ],
> > ```

En que parte debo colocar este código??

**Comment by AkaashK** [comment]
How do I set console config like the above given type..?

**Comment by AkaashK** [comment]
> Hello. You should set this for console config:
> 
> > ```
> > 'controllerMap' => [
> >     'socketio' => [
> >         'ssl' => [
> >             'key' => '/etc/ssl/certs/xxxx.key',
> >             'cert' => '/etc/ssl/certs/xxxx.crt',
> >         ]
> >     ],
> > ],
> > ```

How to set this up?
