### ISSUE TITLE
Failing GET https://localhost:1367/socket.io/?EIO=3&transport=polling&t=...

### ISSUE THREAD

**Issue by vintprox** [yiicod/yii2-socketio#14]
I always get the error in browser console:
`GET https://MYHOSTNAME:1367/socket.io/?EIO=3&transport=polling&t=MVfDGbN net::ERR_CONNECTION_REFUSED`

Running server on VPS: Ubuntu. `telnet MYHOSTNAME 1367` says no connection, while `80` port is just ok.

There are no informative logs on server side, neither those in `runtime/logs/php_server_out.log`:
```
Subscribed to control_channel
Subscribed to testolegit.io
```
(It's appended with every daemon restart.)

You can reproduce similar error when you change port. By the way there is working port occupied by `socket-io-node-js-server` as seen in server's console:

```
$ sudo netstat -peanut | grep ":1367"
tcp        0      0 127.0.0.1:1367          0.0.0.0:*               LISTEN      0          3788254911  19162/node
$ pm2 ls
┌──────────────────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name                 │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────────────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ socket-io-node-js-server │ 0  │ N/A     │ fork │ 19137 │ online │ 0       │ 11m    │ 0%  │ 17.7 MB   │ root │ disabled │
│ socket-io-php-server     │ 1  │ N/A     │ fork │ 19139 │ online │ 0       │ 11m    │ 0%  │ 18.0 MB   │ root │ disabled │
└──────────────────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

What's going on?

Related: #10 
Can you please remember how you solved this issue? @shoxabbos

**Comment by lexxorlov** [comment]
Hello, pls try this #13. It looks like you didn't configure SSL
