### ISSUE TITLE
Code example

### ISSUE THREAD

**Issue by aalex121** [yiicod/yii2-socketio#2]
Hi! Could you please show an example of working code using yii2-socketio?
We have installed the package and started a server, but we have no idea on how could we actually integrate this module into our Yii2 project.
In particular, we can't understand, where event handlers should be placed, and how should we use them in our application.
Some examples of view and controller would be nice!
Used type of Yii2 is advanced.
Thanks in advance!

**Comment by xuananpham93** [comment]
1

**Comment by valeriu-dev** [comment]
+1

**Comment by lexxorlov** [comment]
Hello.
If you use advanced app and you have:
- installed extension by composer.
- installed npm dependency (https://github.com/yiicod/yii2-socketio#install-node--additional-npm)
- configured broadcast (https://github.com/yiicod/yii2-socketio#common-config) in common config
- created in the "frontend" https://github.com/yiicod/yii2-socketio#create-publisher-from-server-to-client and have setted namespace like http://joxi.ru/p277d43sodLpa2
- added yiicod\socketio\SocketIoAsset
- seen in htop(click F5 and group in tree and after F4 and enter "socketio") http://joxi.ru/v29lKGnf3K4jVm If you don't see this image then stop daemon and kill all related process with daemon and run daemon one more time.
	You should not have any errors in: nodejs logs (console/runtime/logs/exceptions.log) and yii2 logs (console/runtime/logs/app.log)

From server to client
Put \yiicod\socketio\Broadcast::emit(CountEvent::name(), ['some_key' => 'some_value']), for example, into SiteController::index and open two index pages. Reload the first index page and you will see console log into second page http://joxi.ru/nAy8jJMuYd9Qp2

Fromt client to server:
Create MarkAsReadEvent (https://github.com/yiicod/yii2-socketio#create-receiver-from-client-to-server) and put into handle method : 
file_put_contents(\Yii::getAlias('@app/runtime/file.txt'), 'test');

Run socketio from client 
var socket = io('localhost:1367/notifications');
socket.emit('mark_as_read_notification', {id: 10});

You will see in the main folder "file.txt" with serialized data

**Comment by WhiteSnowGirl** [comment]
+1

**Comment by lexxorlov** [comment]
Read above

**Comment by neovash23** [comment]
Hi @lexxorlov, 

Can you give a more exact example of this part?
[Create publisher from server to client](https://github.com/yiicod/yii2-socketio#create-publisher-from-server-to-client)

I have created

> backend/socketio/events/CountEvent.php

just added the `namespace backend\socketio\events;`

what does "Changel name. For client side this is nsp" mean?
>   9     /**
 10      * Changel name. For client side this is nsp.
 11      */
 12     public static function broadcastOn(): array
 13     {
 14         return ['notifications'];
 15     }



But how about the view part? this is still not clear yet to me. does the assets get automatically loaded?

and how exactly do we run:

> \yiicod\socketio\Broadcast::emit(CountEvent::name(), ['count' => 10])

getting this response:

> 36:44/notifications,"Invalid namespace"

and I am not really sure what to put in "nsp":
> 12         'broadcastEvents' => [
 13             'class' => \yiicod\socketio\EventManager::class,
 14             'nsp' => '/notifications',
 15             // Namespaces with events folders
 16             'namespaces' => [
 17                 'backend\socketio',
 18             ]
 19         ],

**Comment by lexxorlov** [comment]
Hello!

```
   'broadcastEvents' => [
       'class' => \yiicod\socketio\EventManager::class,
        // **This is prefix for resolve conflicts. If you run on the same server for example two projects**
        'nsp' => 'some_unique_key', 
   ],
```
So you can leave it empty. Don't use symbols. Use some like: "some-key" or "some_key"
For connect assets you should use SocketIoAsset. Or you can configure webpack. 

After you will be able use socket.io client as 
```
   var socket = io('localhost:1367/notifications');
    socket.on('update_notification_count', function(data){
        console.log(data)
    });
```
Run this, you should see in a console log 10
\yiicod\socketio\Broadcast::emit(CountEvent::name(), ['count' => 10])


"what does "Changel name. For client side this is nsp mean?"
This is https://socket.io/docs/rooms-and-namespaces/#namespaces

**Comment by neovash23** [comment]
ah you mean Channel.. but anyway, I finally got it working about 7 hours. Great extension!

**Comment by lexxorlov** [comment]
Thx :+1:  
Would be great if you expand Readme, according on your installation experience. You can write here directly.

**Comment by ankitsinghdalal** [comment]
I have done all the above things mentioned. Now when I start my local server. The pm2 php server start giving error 'No connection could be made because the target machine actively refused it. [tcp://localhost:6379]'

And one more thing I also get 'AccessUnauthorized' in php_server_out.log all the time.
'
