### ISSUE TITLE
Change broadcastOn

### ISSUE THREAD

**Issue by Kutepov** [yiicod/yii2-socketio#20]
Hi. If I change method `broadcastOn`
```
public static function broadcastOn(): array
    {
        return ['anothervalue'];
    }

var socket = io('myhostname:1367/anothervalue');
```

It does not work
What am I doing wrong? Thanks.

**Comment by phuongdev89** [comment]
maybe you still not restart the daemon of socketio
try `php yii socketio/restart` before test again
