### ISSUE TITLE
Yii alias is not correct

### ISSUE THREAD

**Issue by andriibond** [yiicod/yii2-socketio#5]
Hello! I tried to use it extension in ma app. And I came across with one problem when Broadcast.php tried to create a new Process. There is problem with $yiiAlias = '@app/..'. I overrided this alias in my console.php config to 
   'aliases' => [
        '@app/..' => '@app'
    ],
After that, everything worked. But I spent a lot of time to understand this problem. 
Please, fix it in Broadcast.php, the line 29.

**Comment by lexxorlov** [comment]
Hello! Thx for you comment. This problem can be if you use "yii2-app-basic". I will add new param "yiiAlias" for console command.

**Comment by lexxorlov** [comment]
Problem was resolved https://github.com/yiicod/yii2-socketio/blob/master/Process.php#L84 
If you want to set your own path use Yii DI for change it
