### ISSUE TITLE
Process Not found

### ISSUE THREAD

**Issue by neovash23** [yiicod/yii2-socketio#6]
[root@matt-dev yii2socketio]# pm2 start daemons-app.json
[PM2] Applying action restartProcessId on app [socket-io-node-js-server](ids: 0)
[PM2] Applying action restartProcessId on app [socket-io-php-server](ids: 1)
[PM2][ERROR] Process 0 not found
Process not found
[PM2][ERROR] Process 1 not found
Process not found

Getting those error.

**Comment by lexxorlov** [comment]
Run command without pm2:
- socketio/node-js-server
- socket-io-php-server

If they work then problem with pm2 configuration. Read http://pm2.keymetrics.io/docs/usage/cluster-mode/#usage

**Comment by neovash23** [comment]
Hi thanks for the reply, I got it working.
