### ISSUE TITLE
How to list all connected sockets?

### ISSUE THREAD

**Issue by neovash23** [yiicod/yii2-socketio#8]
Hi, 

On the Server side, all I work on is the PHP event classes, but I could not figure out how to get the connected users or sockets. is there a way to do this? all the samples I get is doing it from nodejs. But I am trying to avoid that right now if possible.

I am trying to have an "Online Users" list on my dashboard.

**Comment by lexxorlov** [comment]
Create table and save/find online users by db. Right now it is simple nodejs bridge between php and client

**Comment by lexxorlov** [comment]
@neovash23 I will think about this feature in the future. The main think was, implement tiny bridge for php + socketio.

**Comment by neovash23** [comment]
Yes, and you have done a good job in doing so! thanks!
